#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : thermal_monitor
Version  : 1.8
Release  : 1
URL      : https://github.com/intel/thermal_daemon/archive/v1.8.tar.gz
Source0  : https://github.com/intel/thermal_daemon/archive/v1.8.tar.gz
Summary  : The "Linux Thermal Daemon" program from 01.org
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ GPL-3.0
Requires: thermal_monitor-bin = %{version}-%{release}
Requires: thermal_monitor-config = %{version}-%{release}
Requires: thermal_monitor-data = %{version}-%{release}
Requires: thermal_monitor-license = %{version}-%{release}
Requires: thermal_monitor-man = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
Thermal Daemon monitors and controls platform temperature.

%package bin
Summary: bin components for the thermal_monitor package.
Group: Binaries
Requires: thermal_monitor-data = %{version}-%{release}
Requires: thermal_monitor-config = %{version}-%{release}
Requires: thermal_monitor-license = %{version}-%{release}
Requires: thermal_monitor-man = %{version}-%{release}

%description bin
bin components for the thermal_monitor package.


%package config
Summary: config components for the thermal_monitor package.
Group: Default

%description config
config components for the thermal_monitor package.


%package data
Summary: data components for the thermal_monitor package.
Group: Data

%description data
data components for the thermal_monitor package.


%package license
Summary: license components for the thermal_monitor package.
Group: Default

%description license
license components for the thermal_monitor package.


%package man
Summary: man components for the thermal_monitor package.
Group: Default

%description man
man components for the thermal_monitor package.


%prep
%setup -q -n thermal_daemon-1.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539878516
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1539878516
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/thermal_monitor
cp COPYING %{buildroot}/usr/share/package-licenses/thermal_monitor/COPYING
cp tools/thermal_monitor/qcustomplot/GPL.txt %{buildroot}/usr/share/package-licenses/thermal_monitor/tools_thermal_monitor_qcustomplot_GPL.txt
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/thermald

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/thermald.service

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/org.freedesktop.thermald.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/thermal_monitor/COPYING
/usr/share/package-licenses/thermal_monitor/tools_thermal_monitor_qcustomplot_GPL.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/thermal-conf.xml.5
/usr/share/man/man8/thermald.8
